name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build the project
        run: ./gradlew build

      - name: SonarQube Analysis
        run: ./gradlew sonarqube

      - name: Run Tests
        run: ./gradlew test

      - name: Publish
        run: ./gradlew publish

      - name: Send deployment notification email
        uses: michaelbromley/send-mail-action@v1
        with:
          smtp-server: smtp.yourmailserver.com
          smtp-port: 587
          smtp-user: ${{ secrets.SMTP_USER }}
          smtp-password: ${{ secrets.SMTP_PASSWORD }}
          from: your-email@example.com
          to: recipient-email@example.com
          subject: 'Deployment Completed'
          body: 'The deployment has completed successfully.'
        env:
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
